function []=cw()
% "CW" IS SHORT FOR "CLEAR WORKSPACE"

%% PURPOSE: LITERALLY JUST A SHORTHAND WAY OF CLEARING THE VARIABLE WORKSPACE BECAUSE I'M TIRED OF TYPING CLEARVARS

evalin('caller','clearvars;');